[Options]
DebuggerLogging = true

[ArkhamRevived]
; urls are not directly replaced, only the domain is
; default match is secure bit on and port 443
; so: Match = "domain.com" will work ^
; but you can explicitly set a match too
TitleId = "57520828"
Match = "https://ozzy360-wbid.live.ws.fireteam.net:443"
Redirect = "http://arkhamrevived.kiwifruitdev.com:80"
